feat(backend): export certificate
emjunior258/certeasy pull request #36
Opened 2023-06-04 17:25 UTC by emjunior258

Implements the following API operations:

- `getCertificatePem`
- `getCertificateDer`

2023-06-04 21:09 UTC, snhane requested changes
made some suggestions for some http response codes.

2023-06-04 21:09 UTC, snhane commented on certeasy-backend-app/src/main/java/org/certeasy/backend/common/BaseResource.java
>                                      "Issuer ID Taken", 409,
`return Response.status(Response.Status.CONFLICT.getStatusCode()).entity(new Problem("/problems/issuerId/id-taken",
                                    "Issuer ID Taken", Response.Status.CONFLICT.getStatusCode(),`

2023-06-04 21:09 UTC, snhane commented on certeasy-backend-app/src/main/java/org/certeasy/backend/common/BaseResource.java
>                      .build();
@emjunior258, what if we replace the code number with the actual status?
`return Response.status(Response.Status.NOT_FOUND.getStatusCode()).entity(
                    new Problem("/problems/issuer/not-found",
                                    "Issuer not found", Response.Status.NOT_FOUND.getStatusCode(),
                                    "There no issuer with a matching ID: " + issuerId))
                    .type(MediaType.APPLICATION_JSON_TYPE)
                    .build();`

2023-06-04 21:09 UTC, snhane commented on certeasy-backend-app/src/main/java/org/certeasy/backend/common/cert/NotFoundProblem.java
> +        super(type, title, 404, detail);
replace 404 with `Response.Status.NOT_FOUND.getStatusCode()`?

2023-06-05 05:54 UTC, emjunior258 commented on certeasy-backend-app/src/main/java/org/certeasy/backend/common/cert/NotFoundProblem.java
> +        super(type, title, 404, detail);
I just think `Response.Status.NOT_FOUND.getStatusCode()` is more verbose and less readable. I mean, the status code for NOT_FOUND will never change. We are just writing more code. Also, the enum `Response.Status` doesn't cover all the status we are using, for example: `422`.

2023-06-05 10:59 UTC, merged