fix: create issuer from ref
emjunior258/certeasy pull request #93
Opened 2023-07-18 19:25 UTC by emjunior258

2023-07-19 04:56 UTC, snhane requested changes
@emjunior258, now's just missing the UT reports for core and bouncycastle. 
They've been out for a while now 😅

2023-07-19 20:30 UTC, snhane approved these changes
will address the sonar report later merging

2023-07-19 20:37 UTC, snhane approved these changes

2023-07-20 08:21 UTC, sambodirce approved these changes

2023-07-20 08:22 UTC, merged